-- Table definitions, generated from the exported data.

CREATE TABLE IF NOT EXISTS telemetry.block_telemetry (
    "time" TIMESTAMPTZ,
    "asset_id" TEXT,
    "dc_power_kw" DOUBLE PRECISION,
    "curtailed_power_kw" DOUBLE PRECISION,
    "inverter_ac_power_kw" DOUBLE PRECISION,
    "ac_power_kw" DOUBLE PRECISION,
    "transformer_loss_kw" DOUBLE PRECISION,
    "transformer_loading_pct" DOUBLE PRECISION,
    "active_inverters" BIGINT,
    "date" TEXT,
    "run_id" TEXT,
    "stream" TEXT
);

CREATE INDEX IF NOT EXISTS block_telemetry_asset_time_idx ON telemetry.block_telemetry (asset_id, time DESC);

CREATE TABLE IF NOT EXISTS telemetry.inverter_telemetry (
    "time" TIMESTAMPTZ,
    "asset_id" TEXT,
    "tracker_angle_deg" DOUBLE PRECISION,
    "surface_tilt" DOUBLE PRECISION,
    "poa_global" DOUBLE PRECISION,
    "poa_direct" DOUBLE PRECISION,
    "poa_diffuse" DOUBLE PRECISION,
    "poa_rear" DOUBLE PRECISION,
    "effective_irradiance" DOUBLE PRECISION,
    "cell_temperature" DOUBLE PRECISION,
    "dc_ideal_kw" DOUBLE PRECISION,
    "dc_power_kw" DOUBLE PRECISION,
    "dc_voltage_v" DOUBLE PRECISION,
    "ac_preclip_kw" DOUBLE PRECISION,
    "ac_power_kw" DOUBLE PRECISION,
    "internal_temp_c" DOUBLE PRECISION,
    "thermal_derate_factor" DOUBLE PRECISION,
    "available_power_kw" DOUBLE PRECISION,
    "commanded_power_kw" DOUBLE PRECISION,
    "curtailed_power_kw" DOUBLE PRECISION,
    "operating_state" TEXT,
    "state_reason" TEXT,
    "fault_code" TEXT,
    "date" TEXT,
    "run_id" TEXT,
    "stream" TEXT
);

CREATE INDEX IF NOT EXISTS inverter_telemetry_asset_time_idx ON telemetry.inverter_telemetry (asset_id, time DESC);

CREATE TABLE IF NOT EXISTS telemetry.plant_telemetry (
    "time" TIMESTAMPTZ,
    "total_dc_power_kw" DOUBLE PRECISION,
    "total_inverter_ac_power_kw" DOUBLE PRECISION,
    "collected_ac_power_kw" DOUBLE PRECISION,
    "transformer_loss_kw" DOUBLE PRECISION,
    "collection_loss_kw" DOUBLE PRECISION,
    "substation_power_kw" DOUBLE PRECISION,
    "grid_export_power_kw" DOUBLE PRECISION,
    "poi_limited_kw" DOUBLE PRECISION,
    "curtailed_power_kw" DOUBLE PRECISION,
    "active_blocks" BIGINT,
    "plant_state" TEXT,
    "date" TEXT,
    "run_id" TEXT,
    "stream" TEXT
);

CREATE INDEX IF NOT EXISTS plant_telemetry_time_idx ON telemetry.plant_telemetry (time DESC);

CREATE TABLE IF NOT EXISTS telemetry.transformer_telemetry (
    "time" TIMESTAMPTZ,
    "asset_id" TEXT,
    "input_power_kw" DOUBLE PRECISION,
    "output_power_kw" DOUBLE PRECISION,
    "loading_pct" DOUBLE PRECISION,
    "no_load_loss_kw" DOUBLE PRECISION,
    "load_loss_kw" DOUBLE PRECISION,
    "winding_temp_c" DOUBLE PRECISION,
    "efficiency_pct" DOUBLE PRECISION,
    "date" TEXT,
    "run_id" TEXT,
    "stream" TEXT
);

CREATE INDEX IF NOT EXISTS transformer_telemetry_asset_time_idx ON telemetry.transformer_telemetry (asset_id, time DESC);

CREATE TABLE IF NOT EXISTS telemetry.weather_telemetry (
    "time" TIMESTAMPTZ,
    "asset_id" TEXT,
    "ghi" DOUBLE PRECISION,
    "dni" DOUBLE PRECISION,
    "dhi" DOUBLE PRECISION,
    "clearsky_ghi" DOUBLE PRECISION,
    "clearsky_index" DOUBLE PRECISION,
    "kt_envelope" DOUBLE PRECISION,
    "solar_zenith" DOUBLE PRECISION,
    "temp_air" DOUBLE PRECISION,
    "wind_speed" DOUBLE PRECISION,
    "wind_direction" DOUBLE PRECISION,
    "date" TEXT,
    "run_id" TEXT,
    "stream" TEXT
);

CREATE INDEX IF NOT EXISTS weather_telemetry_asset_time_idx ON telemetry.weather_telemetry (asset_id, time DESC);

-- Generated by northstar_sim.storage.generate_ddl.
-- Schemas and roles are created by db/init/01_schemas.sql.
-- Table definitions come from generate_table_ddl and must be applied
-- first: create_hypertable requires the table to already exist.

